-- Business Problems
-- 1. The restaurant wants to reward its most valuable customers with loyalty discounts. (Top 5 Customers by Total Spending)
SELECT
    C.CustomerID,
    C.CustomerName,
    SUM(O.TotalAmount) AS TotalSpent
FROM Customers C
JOIN Orders O
ON C.CustomerID = O.CustomerID
GROUP BY C.CustomerID, C.CustomerName
ORDER BY TotalSpent DESC
LIMIT 5;

-- 2. Marketing wants to contact registered customers who have never visited after registration. (Customers Who Never Placed an Order)
SELECT
    CustomerID,
    CustomerName
FROM Customers
WHERE CustomerID NOT IN
(
    SELECT CustomerID
    FROM Orders
);

-- 3. Management wants to know how much an average customer spends.
SELECT
    C.CustomerID,
    C.CustomerName,
    AVG(O.TotalAmount) AS AverageSpending
FROM Customers C
JOIN Orders O
ON C.CustomerID = O.CustomerID
GROUP BY C.CustomerID, C.CustomerName;

-- 4. Identify repeat customers for loyalty rewards.
SELECT
    C.CustomerName,
    COUNT(O.OrderID) AS TotalOrders
FROM Customers C
JOIN Orders O
ON C.CustomerID = O.CustomerID
GROUP BY C.CustomerID, C.CustomerName
HAVING COUNT(O.OrderID) > 1;

-- 5. The manager wants to review the latest customer orders.
SELECT
    O.OrderID,
    C.CustomerName,
    O.OrderDate,
    O.TotalAmount
FROM Orders O
JOIN Customers C
ON O.CustomerID = C.CustomerID
ORDER BY O.OrderDate DESC;

-- 6. Calculate total revenue generated.
-- Shows overall business performance.
SELECT
SUM(TotalAmount) AS TotalRevenue
FROM Orders;

-- 7. Management wants daily sales.
-- Helps identify busy days.
SELECT
DATE(OrderDate) AS SalesDate,
SUM(TotalAmount) AS Revenue
FROM Orders
GROUP BY DATE(OrderDate)
ORDER BY SalesDate;

-- 8. Management wants monthly revenue trends.
SELECT
MONTH(OrderDate) AS Month,
SUM(TotalAmount) AS Revenue
FROM Orders
GROUP BY MONTH(OrderDate)
ORDER BY Month;

-- 9. Find the largest order ever placed.
SELECT *
FROM Orders
WHERE TotalAmount =
(
SELECT MAX(TotalAmount)
FROM Orders
);

-- 10. Best Selling Menu Item
SELECT
M.ItemName,
SUM(OD.Quantity) AS QuantitySold
FROM MenuItems M
JOIN OrderDetails OD
ON M.ItemID = OD.ItemID
GROUP BY M.ItemID, M.ItemName
ORDER BY QuantitySold DESC
LIMIT 1;

-- 11. Revenue Generated by Each Category 
SELECT
C.CategoryName,
SUM(OD.Subtotal) AS Revenue
FROM Categories C
JOIN MenuItems M
ON C.CategoryID = M.CategoryID
JOIN OrderDetails OD
ON M.ItemID = OD.ItemID
GROUP BY C.CategoryID, C.CategoryName
ORDER BY Revenue DESC;

-- 12. Waiter Handling Most Orders
SELECT
E.EmployeeName,
COUNT(O.OrderID) AS OrdersHandled
FROM Employees E
JOIN Orders O
ON E.EmployeeID = O.EmployeeID
WHERE E.Role='Waiter'
GROUP BY E.EmployeeID, E.EmployeeName
ORDER BY OrdersHandled DESC
LIMIT 1;

-- 13. Employee Salary Ranking
SELECT
EmployeeName,
Salary,
RANK() OVER(ORDER BY Salary DESC) AS SalaryRank
FROM Employees;

-- 15. Highest Paid Employee
SELECT
EmployeeName,
Salary
FROM Employees
ORDER BY Salary DESC
LIMIT 1;

-- 16. Available vs Occupied Tables
SELECT
Status,
COUNT(*) AS TotalTables
FROM RestaurantTables
GROUP BY Status;

-- 17. Peak Ordering Hour
SELECT
HOUR(OrderDate) AS OrderHour,
COUNT(*) AS TotalOrders
FROM Orders
GROUP BY HOUR(OrderDate)
ORDER BY TotalOrders DESC
LIMIT 1;

-- 18. Top 3 Selling Items in Each Category
SELECT *
FROM
(
    SELECT
        C.CategoryName,
        M.ItemName,
        SUM(OD.Quantity) AS QuantitySold,
        DENSE_RANK() OVER
        (
            PARTITION BY C.CategoryName
            ORDER BY SUM(OD.Quantity) DESC
        ) AS Ranking
    FROM Categories C
    JOIN MenuItems M
    ON C.CategoryID = M.CategoryID
    JOIN OrderDetails OD
    ON M.ItemID = OD.ItemID
    GROUP BY C.CategoryName, M.ItemName
) AS RankedItems
WHERE Ranking <= 3;

